version: '1'
services:
  nvidia-cuda-encode-video-stream:
    image: jarvan12th/nvidia-cuda-encode-video-stream:v1.0
    command: uvicorn main:app --host 0.0.0.0 --port 4000 --reload
    volumes:
      - ./main.py:/app/main.py
    ports:
      - "4000:4000"
    depends_on:
      - rtmp-server

  rtmp-server:
    image: "alqutami/rtmp-hls:latest"
    ports:
      - "1935:1935"  # Default port for RTMP
      - "8080:8080"  # Default port for HTTP where HLS can be accessed